# Generated by Django 4.1.5 on 2023-01-25 18:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('IN_TRANSIT', 'in_transit'), ('DELIVERED', 'delivered')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 1, 25, 18, 46, 31, 975682), verbose_name='Created At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
    ]
